version: "3.6"

services:
  mysqldb:
    container_name: MYSQL
    image: mysql
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=Prod
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
volumes:
  db_data:
  Arquivos:
networks:
  default:
    name: sistema_default
